

```
# Выбран кодовый формат
```

# Вычисления с помощью NumPy

## Многомерные массивы в NumPy

Библиотека `numpy` поддерживает работу с многомерными массивами, в том числе, с матрицами, и очень хороша для научных расчётов. Библиотека написана не только на `Python`, но и на языке `C`, который является более низкоуровневым и работает значительно быстрее, поэтому расчёты в `numpy` производятся во много раз быстрее, чем если бы мы использовали для этого стандартные структуры данных из `Python`.

Установить библиотеку `numpy` можно следующим образом:

* Если вы используете `Python` в составе дистрибутива `Anaconda`, то достаточно в командной строке ввести:   
`conda install numpy`

* Если вы используете `Python` отдельно, то же самое можно сделать с помощью пакетного менеджера `pip`:   
`pip install numpy`

In [1]:
import numpy as np

Чтобы задать `numpy`-массив, достаточно задать обычный питоновский список `list`, а затем поместить его внутрь функции `np.array`:

In [2]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


Внутрь этой функции можно подавать также питоновский кортеж `tuple`.

Проверим, к какому типу относится массив `a`:

In [3]:
type(a)

numpy.ndarray

`ndarray` - сокращение от $n$-dimensional array ($n$-мерный массив).

В отличие от стандартных питоновских структур данных, в `numpy` массивы предпочитают данные одного типа. Например, если функция `np.array` вызывается от списка, содержащего как целые (`int`), так и дробные (`float`) значения, то в результирующем массиве все значения будут приведены к типу `float`. Аналогично, если в подаваемом списке есть хотя бы одна строка `str`, то в соответствующем массиве все значения будут приведены к типу `str`. Если мы хотим задать свой тип, к которому нужно привести данные, это можно сделать с помощью аргумента `dtype`:

In [4]:
a = np.array([1, 2, 3.6], dtype=str)

print(a)

['1' '2' '3.6']


Получить конкретный элемент массива можно теми же способами, что и в стандартных питоновских структурах данных - с помощью квадратных скобок. В `numpy`, как и во всём питоне, индексация начинается с нуля. Например, получить второй элемент из массива `a` (т.е. элемент с индексом $1$) можно так:

In [5]:
a[1]

'2'

[Текст ссылки](https://)Также в `numpy` массивах можно использовать отрицательную индексацию и делать срезы, как и в стандартных списках из питона:

In [6]:
a[-1]

'3.6'

In [7]:
a[1:3]

array(['2', '3.6'], dtype='<U3')

### Двумерные массивы

Пока что мы работали лишь с одномерными массивами. Также в `numpy` можно задать и многомерные массивы. Например, двумерный массив - это массив, каждый элемент из которого - это снова массив.

Для `numpy`-массива `a` можно проверить его размерность с помощью атрибута `ndim` и форму с помощью атрибута `shape`:

In [8]:
print("Размерность a: {}".format(a.ndim))

print("Форма a: {}".format(a.shape))

Размерность a: 1
Форма a: (3,)


В этом случае размерность равна $1$, а `shape` возвращает кортеж из одного элемента. Зададим теперь двумерный массив:

In [9]:
A = np.array([[1, 2, 3, 1], 
              [4, 5, 6, 4], 
              [7, 8, 9, 7]])

print(A)

print("Размерность A: {}".format(A.ndim))

print("Форма A: {}".format(A.shape))

[[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]]
Размерность A: 2
Форма A: (3, 4)


Атрибут `shape` - это всегда кортеж, размер которого равен размерности массива. Каждый элемент этого кортежа - это размер в каждом измерении. Например, у нашей матрицы $A$, судя по этому атрибуту, $3$ строки и $4$ столбца.

С помощью атрибута `size` можно увидеть общее количество элементов массива:

In [10]:
A.size

12

В случае вложенных друг в друга стандартных питоновских списков `list`, чтобы получить конкретный элемент массива, нужно использовать несколько пар квадратных скобок: `A[0][0]`. В `numpy` массивы также поддерживают такую запись, однако, здесь есть и более удобный вариант - просто писать индексы через запятую:

In [11]:
A[0, 0]

1

Это же работает и в случае отрицательной индексации и в случае срезов:

*   Новый пункт
*   Новый пункт

In [12]:
A[-1, -2]

9

In [13]:
A[1:, :3]

array([[4, 5, 6],
       [7, 8, 9]])

В случае срезов для `numpy`-массивов важно отметить, что, записывая срез `numpy`-массива, мы ничего нового не создаём, мы лишь получаем _представление_ (_view_) - ссылку на какие-то отдельные элементы оригинального массива. Это означает, что если мы "создали" срез из `numpy`-массива, а затем поменяли в нём что-то - эти изменения коснутся и оригинального массива:

In [14]:
print(A)

[[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]]


In [15]:
B = A[1:, :3]

print(B)

[[4 5 6]
 [7 8 9]]


In [16]:
B[0, 0] = -4

print(A)

[[ 1  2  3  1]
 [-4  5  6  4]
 [ 7  8  9  7]]


Наоборот, если мы меняем значения в оригинальном массиве, они коснутся и всех его представлений, в которых используются эти значения:

In [17]:
A[2, 0] = -7

print(B)

[[-4  5  6]
 [-7  8  9]]


In [18]:
b = np.array([[3], 
     [1], 
     [2]])



```
# Выбран кодовый формат
```

Если мы хотим всего этого избежать и создать действительно новый массив, нужно использовать метод `copy`:

In [19]:
C = A[1:3, 2:4].copy()

print(C)

[[6 4]
 [9 7]]


In [20]:
C[0, 0] = -6

print(A)

[[ 1  2  3  1]
 [-4  5  6  4]
 [-7  8  9  7]]


### Типы данных в NumPy

Самыми распространёнными типами в `numpy` являются два целочисленных типа: `np.int32` и `np.int64` и два дробных типа: `np.float32` и `np.float64`. Они применяются для, соответственно, $32$-битных и $64$-битных чисел. Последние требуют вдвое больше памяти, чем первые, однако, если вы знаете, что в вашем массиве, например, используются целые числа, которые по модулю больше, чем $2 \cdot 10^9$, то стоит использовать `np.int64`.

### Операции с векторами

In [21]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 7, 8, 9])

Сейчас мы ограничимся случаем, когда все векторы имеют одинаковый размер.

Сложение векторов можно выполнять, просто складывая массивы. Отметим, что это поведение отличается от сложения обычных питоновских списков `list`: списки в таком случае просто склеиваются в один.

In [22]:
a_ = [0, 1, 2, 3, 4]
b_ = [5, 6, 7, 8, 9]

c_ = a_ + b_

print(c_)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


В `numpy` же массивы в результате такой операции складываются поэлементно:

In [23]:
c = a + b

print(c)

[ 5  7  9 11 13]


Также массивы `numpy` можно складывать с помощью функции `np.add`:

In [24]:
c = np.add(a, b)

print(c)

[ 5  7  9 11 13]


Аналогично, есть два способа вычитать векторы друг из друга:

* `d = a - b`
* `d = np.subtract(a, b)`

Для умножения вектора на скаляр также можно пользоваться достаточно естественной записью:

In [25]:
e = a * 3

print(e)

[ 0  3  6  9 12]


При этом скаляр может быть каким угодно. При умножении на скаляр, каждая координата вектора умножается на этот скаляр.

Это поведение тоже отличается от поведения питоновских списков `list` при умножении на число. Последние при этом дублируются заданное количество раз. Скаляр здесь, кроме того, может быть только положительным целым.

In [26]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

Вот ещё несколько способов умножить вектор на скаляр в `numpy`:

* с помощью функции `np.multiply`: `e = np.multiply(a, 3)`
* с помощью функции `np.dot`: `e = np.dot(a, 3)`
* с помощью метода `a.dot`, который есть у любого `numpy`-массива: `e = a.dot(3)`

Функция `np.dot` (так же, как и метод `a.dot`), кроме того, может вычислять скалярное произведение векторов, а также произведение матриц (об этом чуть позже). 

Посчитаем скалярное произведение векторов `a` и `b`. Напомним, что чтобы вычислить скалярное произведение двух векторов, нужно попарно перемножить их координаты (первую с первой, вторую со второй и т.д.), а затем сложить результаты.

In [27]:
sp = a.dot(b)

print(sp)

80


Также скалярное произведение векторов можно вычислять с помощью оператора `@`:

In [28]:
sp = a @ b

print(sp)

80


### Матрицы

Разберёмся теперь, как в `numpy` работать с матрицами. Зададим пару матриц:

In [29]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

Матрицы одинакового размера можно складывать и вычитать. Как и с векторами, это можно делать с помощью операторов `+` и `-`, а также с помощью функций `np.add` и `np.subtract`.

In [30]:
C = A + B

print(C)

[[ 6  8]
 [10 12]
 [14 16]]


In [31]:
D = A - B

print(D)

[[-6 -6]
 [-6 -6]
 [-6 -6]]


Матрицу любого размера можно умножать на скаляр. Делается это так же, как и в случае векторов:

In [32]:
E = A * 3

print(E)

[[ 0  3]
 [ 6  9]
 [12 15]]


### Умножение матриц

Матрицы $A$ и $B$ можно умножить друг на друга, если _число столбцов_ первой матрицы равняется _числу строк_ второй матрицы. То есть если $A$ - матрица размера $n \times k$, то матрица $B$ должна иметь размер $k \times m$ для некоторого $m$.

В таком случае результатом умножения будет матрица $C$ размера $n \times m$ (т.е. у неё будет строк как у первой матрицы, а столбцов - как у второй).

Рассмотрим простейший случай: умножение строки (матрицы размера $1 \times k$) на столбец (матрицу размера $k \times 1$). Как мы уже выяснили, в результате получится матрица размера $1 \times 1$, т.е. число. Что это за число?

Чтобы посчитать это число, нужно элементы из строки и столбца попарно перемножить (первый с первым, второй со вторым и т.д.), а затем сложить результаты. Это очень похоже на скалярное произведение векторов.

Например, 

$$
\left(
\begin{matrix}
    1 & 2 & 3
\end{matrix}
\right)
\cdot
\left(
\begin{matrix}
    1 \\
    0 \\
    -1
\end{matrix}
\right)
= 1 \cdot 1 + 2 \cdot 0 + 3 \cdot (-1)
= -2.
$$

Вернёмся к общему случаю - умножению матрицы размера $n \times k$ на матрицу размера $k \times m$. Мы уже поняли, что это будет матрица размера $n \times m$. Как "заполнить" эту матрицу?

Чтобы получить число, стоящее в этой матрице на позиции $(i, j)$, нужно умножить $i$-ю строку первой матрицы на $j$-й столбец второй матрицы (так, как мы это делали выше).

Например,

$$
\left(
\begin{matrix}
    1 & 0 & -1 \\
    3 & 5 & -4 
\end{matrix}
\right)
\cdot
\left(
\begin{matrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9
\end{matrix}
\right)
=
\left(
\begin{matrix}
    1 \cdot 1 + 0 \cdot 4 + (-1) \cdot 7 & 1 \cdot 2 + 0 \cdot 5 + (-1) \cdot 8 & 1 \cdot 3 + 0 \cdot 6 + (-1) \cdot 9 \\
    3 \cdot 1 + 5 \cdot 4 + (-4) \cdot 7 & 3 \cdot 2 + 5 \cdot 5 + (-4) \cdot 8 & 3 \cdot 3 + 5 \cdot 6 + (-4) \cdot 9
\end{matrix}
\right)
=
$$

$$
=
\left(
\begin{matrix}
    -6 & -6 & -6 \\
    -5 & -1 & 3
\end{matrix}
\right).
$$

Чтобы выполнять умножение матриц в библиотеке `numpy`, будем пользоваться уже знакомой функцией `np.dot`, либо методом `A.dot`:

In [33]:
A = np.array([[1, 0, -1],
              [3, 5, -4]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

C = A.dot(B)

print(C)

[[-6 -6 -6]
 [-5 -1  3]]


Если перемножаемые матрицы являются квадратными, то результат их умножения будет снова квадратной матрицей, причём, того же размера. Это означает, что квадратную матрицу можно возводить в степень. В `numpy` это можно делать с помощью функции `matrix_power` из модуля `numpy.linalg`:

In [34]:
D = np.linalg.matrix_power(B, 3)

print(D)

[[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]


### Единичная и транспонированная матрица

_Единичной матрицей_ называется квадратная матрица, у которого на главной диагонали стоят $1$, а в остальных местах - $0$. (Под _главной диагональю_ мы понимаем диагональ матрицы, которая начинается в левом верхнем углу и заканчивается в правом нижнем.) Единичную матрицу можно задать с помощью функции `np.eye`:

In [35]:
I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


При умножении любой матрицы на единичную матрицу подходящего размера, результатом будет та же самая матрица:

In [36]:
print(A)

[[ 1  0 -1]
 [ 3  5 -4]]


In [37]:
E = A.dot(I)

print(E)

[[ 1.  0. -1.]
 [ 3.  5. -4.]]


Пусть дана матрица $A$. _Транспонированной матрицей_ называется матрица $A^\top$, полученная "отражением" матрицы $A$ относительно её главной диагонали. Другими словами, столбцы матрицы $A$ становятся строками матрицы $A^\top$, а строки матрицы $A$ - столбцами матрицы $A^\top$.

Вот несколько способов посчитать транспонированную матрицу в `numpy`:

* с помощью функции `np.transpose`: `A_t = np.transpose(A)`
* с помощью метода `A.transpose`: `A_t = A.transpose()`
* с помощью атрибута `A.T`: `A_t = A.T`

In [38]:
A_t = A.T

print(A_t)

[[ 1  3]
 [ 0  5]
 [-1 -4]]


### Определитель и ранг матрицы

Если матрица квадратная, то мы можем посчитать её _определитель_. Определитель матрицы - это число, которое в каком-то смысле "определяет" её свойства. Например, обратную матрицу можно посчитать только для матрицы, определитель которой не равен $0$ (по аналогии с тем, что делить можно только на числа, не равные $0$).

Посчитать определитель можно с помощью функции `det` из модуля `numpy.linalg`:

In [39]:
d = np.linalg.det(B)

print(d)

-9.51619735392994e-16


Также с помощью функции `matrix_rank` из модуля `numpy.linalg` можно посчитать _ранг_ матрицы. Ранг матрицы - это число линейно независимых строк данной матрицы.

In [40]:
r = np.linalg.matrix_rank(B)

print(r)

2


Если матрица квадратная, то её ранг и определитель связаны следующим образом: определитель матрицы отличен от $0$ тогда и только тогда, когда все её строки являются линейно независимыми. Это, в свою очередь, означает, что её ранг равен её размеру.

Например, ранг матрицы $B$ из примера выше равен $2$, при этом её размер равен $3$. Это значит, что не все её строки являются линейно независимыми, поэтому её определитель равен $0$.

В отличие от определителя, ранг можно считать и для матрицы, которая не является квадратной. Посчитаем ранг матрицы $A$ размера $2 \times 3$, определённой выше:

In [41]:
r1 = np.linalg.matrix_rank(A)

print(r1)

2


Итак, если определитель квадратной матрицы не равен $0$, то мы можем посчитать для неё _обратную матрицу_. Это матрица, которая при умножении на исходную матрицу даёт единичную матрицу:

$$A \cdot A^{-1} = I$$

Обратную матрицу можно посчитать с помощью функции `inv` из модуля `numpy.linalg`:

In [42]:
F = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

print(np.linalg.det(F))

85.99999999999997


In [43]:
F_inv = np.linalg.inv(F)

print(F_inv)

[[ 0.18604651  0.02325581 -0.08139535]
 [-0.97674419  0.62790698  0.30232558]
 [ 0.72093023 -0.53488372 -0.12790698]]


Проверим, что условие действительно выполняется:

In [44]:
print(F.dot(F_inv))

[[ 1.00000000e+00  0.00000000e+00  1.11022302e-16]
 [-2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [-4.44089210e-16  0.00000000e+00  1.00000000e+00]]


Если определитель матрицы $A$ равен $d$, то определитель обратной матрицы всегда будет равен $1/d$. Именно поэтому матрицы с определителем, равным $0$, обращать нельзя.

In [45]:
F_d = np.linalg.det(F)

F_inv_d = np.linalg.det(F_inv)

print(F_d * F_inv_d)

1.0


## Генерирование массивов с заданными свойствами

Здесь мы рассмотрим способы задавать массивы различных размеров.

Функция `np.zeros` позволяет создать массив любой формы, состоящий из нулей:

In [46]:
a = np.zeros((3, 4))

print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Аналогично, функция `np.ones` вернёт массив заданной формы, состоящий из единиц:

In [47]:
b = np.ones((3, 4))

print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Последовательности чисел можно создавать с помощью функции `np.arange`. Вот три способа использовать эту функцию:

* Если задать только один аргумент, то вернётся последовательность чисел от $0$ до этого аргумента невключительно:

In [48]:
ar1 = np.arange(10)

print(ar1)

[0 1 2 3 4 5 6 7 8 9]


* Если подать два аргумента, то вернётся последовательность чисел от первого аргумента до второго (включая первый, не включая второй):

In [49]:
ar2 = np.arange(2, 13)

print(ar2)

[ 2  3  4  5  6  7  8  9 10 11 12]


* Если подать три аргумента, то третий аргумент будет обозначать шаг, с которым берутся числа в последовательности:

In [50]:
ar3 = np.arange(2, 13, 2)

print(ar3)

[ 2  4  6  8 10 12]


Отметим, что шаг в функции `np.arange` может быть дробным:

In [51]:
ar4 = np.arange(2, 3, 0.1)

print(ar4)

[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


Если шаг отрицательный, то последовательность будет возвращена в обратном порядке:

In [52]:
ar5 = np.arange(3, 2, -0.1)

print(ar5)

[3.  2.9 2.8 2.7 2.6 2.5 2.4 2.3 2.2 2.1]


Ещё одна полезная функция здесь - это функция `np.linspace`. Она позволяет вернуть заданное количество значений, равномерно расставленных между заданными началом и концом отрезка. Отметим, что здесь и левый, и првый концы отрезка включаются в массив:

In [53]:
c = np.linspace(2, 3, 10)

print(c)

[2.         2.11111111 2.22222222 2.33333333 2.44444444 2.55555556
 2.66666667 2.77777778 2.88888889 3.        ]


Функция `np.logspace` имеет похожий эффект, отличие лишь в том, что в качестве начала и конца отрезка мы подаём не сами числа, а степени числа $10$. Например, в ячейке ниже мы задаём массив, содержащий $4$ значения, расставленных равномерно в пределах от $10^0 = 1$ до $10^3 = 1000$.

In [54]:
d = np.logspace(0, 3, 4)

print(d)

[   1.   10.  100. 1000.]


### Массивы случайных значений

Функция `sample` из модуля `numpy.random` возвращает массив заданной формы, состоящий из чисел, взятых из равномерного распределения на отрезке $[0, 1)$.

In [55]:
a = np.random.sample((3, 4))

print(a)

[[0.20691838 0.27717055 0.94751153 0.17850731]
 [0.1140571  0.15780823 0.25242265 0.02259075]
 [0.89343722 0.6065849  0.83363851 0.48893723]]


Отметим, что в эту и другие представленные ниже функции можно подавать также не кортеж, а какое-то одно целое число. В этом случае вернётся одномерный массив заданного размера. Также в эти функции можно не подавать аргументы вовсе - в этом случае вернётся лишь одно число.

In [56]:
print("Одно значение: {}".format(np.random.sample()))

print("Три значения: {}".format(np.random.sample(3)))

Одно значение: 0.5926690352536381
Три значения: [0.38209553 0.2571937  0.34922992]


Функция `randn` из модуля `numpy.random` возвращает аналогичный массив, но уже взятый из нормального распределения (со средним $0$ и среднеквадратическим отклонением $1$):

In [57]:
b = np.random.randn(3, 4)

print(b)

[[-0.41691347 -0.07556481  1.43240746 -0.05961375]
 [-0.70692721 -0.28491981  0.2037674   1.56064524]
 [ 1.03852182 -0.04385046  0.60046454 -0.73711777]]


Обратите внимание, что эта функция получает на вход не кортеж `tuple`, а просто последовательность размеров по каждому измерению.

Функция `randint` возвращает массив из целых чисел в указанном диапазоне:

In [58]:
c = np.random.randint(0, 100, (3, 4))

print(c)

[[64 17 35 64]
 [90 28 37 58]
 [ 4 20 69 30]]


Функция `choice` возвращает случайно выбранные элементы из заранее заданного массива:

In [59]:
A = np.arange(-10, 0)

d = np.random.choice(A, (3, 4))

print(d)

[[-10 -10  -4  -8]
 [ -5  -7 -10  -2]
 [ -3  -1  -1  -7]]


### Изменение размеров массива

Библиотека `numpy` предоставляет функционал для удобного изменения размера массивов.

Например, рассмотрим одномерный массив с $12$ элементами:

In [60]:
ar = np.arange(12)

print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


Если нам нужно расположить эти значения в двумерном массиве, мы можем сделать это с помощью функции `np.reshape` или метода `ar.reshape`:

In [61]:
a = ar.reshape(3, 4)

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Ясно, что при этом число элементов получаемого массива должно совпадать с числом элементов в оригинальном массиве. Например, следующая попытка посчитать функцию закончится ошибкой:

In [62]:
b = ar.reshape(3, 5)

ValueError: cannot reshape array of size 12 into shape (3,5)

Если мы знаем количество строк, которое хотим получить, но не знаем количество столбцов, в качестве второго аргумента можно передать число $-1$. Если наоборот мы знаем лишь количество столбцов, можно передать $-1$ в качестве первого аргумента.

In [ ]:
b = ar.reshape(3, -1)

print(b)

Метод `ar.reshape` не меняет сам массив `ar`, он лишь возвращает новый. Есть также метод `ar.resize`, который делает то же самое, что и `ar.reshape`, но не возвращает ничего и меняет исходный массив:

In [ ]:
ar.resize(3, 4)

print(ar)

Обратно, чтобы получить из многомерного массива одномерный, можно воспользоваться методом `ar.flatten`:

In [ ]:
c = ar.flatten()

print(c)

### Соединение массивов

Рассмотрим два массива и разберёмся с тем, как их можно соединить в один.

In [ ]:
a = np.zeros((2, 3))

b = np.ones((2, 3))

Мы можем соединить эти массивы вертикально (т.е. дописать один под другим). Вот несколько способов это сделать:

* с помощью функции `np.vstack`: `c = np.vstack((a, b))` (получает на вход кортеж из массивов)
* с помощью функции `np.concatenate`: `c = np.concatenate((a, b), axis=0)` (тоже получает на вход кортеж, также нужно указать, вдоль какой оси производится конкатенация)

In [ ]:
c = np.vstack((a, b))

print(c)

Также несколько способов это соединить массивы горизонтально (т.е. дописать один правее другого):

* с помощью функции `np.hstack`: `c = np.hstack((a, b))`
* с помощью функции `np.concatenate`: `c = np.concatenate((a, b), axis=1)` (производится теперь вдоль оси $1$)

In [ ]:
d = np.concatenate((a, b), axis=1)

print(d)

Наконец, два двумерных массива можно соединить _в глубину_ (т.е. вдоль новой третьей оси) с помощью функции `np.dstack`:

In [ ]:
e = np.dstack((a, b))

print(e)

## Функции для работы с данными

Библиотека `numpy` предлагает удобный функционал для выбора данных из массива. Рассмотрим массив из $10$ случайных целых значений от $0$ до $19$:

# Новый раздел

In [ ]:
a = np.random.randint(0, 20, 10)

print(a)

Допустим, мы хотим выбрать все значения этого массива, которые больше $10$. Вот как это можно сделать:

In [ ]:
b = a[a > 10]

print(b)

*Свойства* можно комбинировать, используя логические операторы "и" (обозначается символом $\&$), "или" (символ $\mid$) и оператор отрицания "не" (символ $\sim$). При этом каждое условие необходимо поставить в круглые скобки:

In [ ]:
c = a[(a > 0) & (a % 2 == 0)]

print(c)

Такая конструкция в `numpy` называется _булевой индексацией_. Разберёмся с ней поподробнее. Что из себя представляет объект `a > 0`?

In [ ]:
print(a > 10)

Как мы видим, это просто `numpy`-массив из булевых значений `True` и `False`. Когда мы подставляем такой массив в качестве _индекса_ массива `a`, нам возвращаются все элементы, на позиции которых в этом массиве стоит значение `True`.

Можно просто создать такой массив вручную и передать его в качестве индекса:

In [ ]:
ind = np.array([True, False, True, True, False, False, False, True, True, False])

print(a[ind])

Другой способ выбрать значения из массива - с помощью функции `np.where`. Она берёт массив из булевых значений и возвращает _индексы_ истинных значений:

In [ ]:
ind1 = np.where(a > 10)

print(ind1)

Такой список индексов можно также передать в массив `a` чтобы получить конкретные значения:

In [ ]:
d = a[ind1]

print(d)

То же самое можно сделать и вручную: передать в квадратные скобки массива `a` какой-нибудь список из индексов:

In [ ]:
e = a[[0, 4, 7]]

print(e)

Отметим также, что если массив `a` является многомерным, то чтобы выбрать таким образом из него значения, нужно указать внутри квадратных скобок через запятую столько списков, сколько имеется у массива измерений:

In [ ]:
a.resize((5, 2))

print(a)

In [ ]:
f = a[[1, 4], :]

print(f)

### Сортировка

Рассмотрим двумерный массив:

In [ ]:
a = np.random.randint(0, 6, (3, 4))

print(a)

Допустим, мы хотим отсортировать строки этого массива по второму столбцу. Мы можем сделать это вручную, задав индексы строк в нужном нам порядке:

In [ ]:
b = a[[1, 2, 0], :]

print(b)

Этот процесс можно автоматизировать с помощью метода `a.argsort`. Данный метод возвращает массив из индексов массива `a` в порядке их возрастания по заданной оси:

In [ ]:
ind = a.argsort(axis=0)

print(ind)

В каждом столбце этого массива стоят индексы строк массива `a`, расположенные в том порядке, в котором они бы отсортировали данный столбец по возрастанию. Автоматизируем процесс сортировки массива `a` по второму столбцу. Для этого нужно получить второй столбец из массива, полученного с помощью метода `a.argsort`:

In [ ]:
ind1 = a[:, 1].argsort()

print(ind1)

Итоговая конструкция будет выглядеть так:

In [ ]:
c = a[a[:, 1].argsort(), :]

print(c)

### Перемешивание

Иногда оказывается нужно перемешать значения массива. Это можно сделать с помощью функции `shuffle` из модуля `numpy.random`. Эта функция ничего не возвращает, лишь перемешивает случайным образом элементы данного массива. Отметим, что она перемешивает массив только в первом измерении. Другими словами, если массив двумерный, она лишь переставит его строки местами. Содержимое самих строк при этом не изменится:

In [ ]:
np.random.shuffle(c)

print(c)

### Математические операции над массивами

Некоторые математические операции можно выполнять с массивами целиком. Например, мы уже знаем, что массивы можно умножать на число и что массивы одинаковой формы можно складывать.

In [ ]:
a = np.arange(0, 6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

print(a)
print(b)

In [ ]:
print(a + b)

In [ ]:
print(a * 2)

К массивам можно также прибавлять числа - в этом случае к каждому элементу массива прибавляется число:

In [ ]:
print(a + 1)

Массивы одинакового размера можно поэлементно умножать. (Важно не путать с матричным умножением.)

In [ ]:
print(a * b)

С помощью метода `a.sum` можно посчитать сумму всех значений массива. Если указать в этом методе ось `axis`, сумма будет посчитана только вдоль этой оси:

In [ ]:
print("Сумма всех элементов: {}".format(a.sum()))

print('Сумма по столбцам ("вдоль" строк): {}'.format(a.sum(axis=0)))

print('Сумма по строкам ("вдоль" столбцов): {}'.format(a.sum(axis=1)))

#### Broadcasting

В определённых случаях мы можем выполнять операции сложения и умножения над матрицами разных размеров. Концепция _broadcasting_ заключается в том, что в некоторых случаях интерпретатор "догадывается", что одну массив надо в каком-то измерении "растянуть" до соответствия со вторым массивом. Рассмотрим массив размера $3 \times 2$:

In [ ]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])

а также одномерный массив размера $2$:

In [ ]:
b = np.array([1, 2])

Если мы попытаемся их сложить, интерпретатор заметит, что у них совпадает одно из измерений: у них обоих $2$ столбца. Поэтому интерпретатор как бы "растянет" массив `b` до размера $2 \times 3$ и прибавит его к массиву `a`:

In [ ]:
c = a + b

print(c)

На самом деле здесь строка `b` просто прибавится к каждой строке массива `a`.

Аналогично можно поступить и со столбцами:

In [ ]:
d = np.array([[0],
              [1],
              [-1]])

e = a + d

print(e)

Интерпретатор заметит, что у этих массивов совпадает число строк, поэтому "растянет" массив `d` до размера массива `a`. Попросту говоря, столбец `b` прибавится к каждому из столбцов массива `a`.

Имеются и более сложные конструкции broadcasting, о них можно почитать [здесь](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

В случае, когда размеры массивов согласовать не удаётся, выпадает ошибка:

In [ ]:
f = np.array([0, 1, -1])

a + f

#### Статистические функции

Вот несколько методов, позволяющих вычислить различные статистики массива `a`:

* `a.min` - минимальное значение
* `a.max` - максимальное значение
* `a.mean` - среднее значение
* `a.std` - среднее квадратическое отклонение

Все эти значения считаются по всему массиву, либо вдоль определённой оси, если задан параметр `axis`.

In [ ]:
print(a)

In [ ]:
print("Минимальное значение: {}".format(a.min()))

print("Средние значения строк: {}".format(a.mean(axis=1)))

print("Средние квадратические отклонения столбцов: {}".format(a.mean(axis=0)))

### Запись и чтение массивов из файла

Массивы `numpy` можно сохранять в файлы с расширением `.npy` и читать из таких файлов.

Для записи массива в файл используется функция `np.save`:

In [ ]:
np.save("a.npy", a)

Для чтения из файла используется функция `np.load`:

In [ ]:
a = np.load("a.npy")

# Домашнее задание

### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [65]:
import numpy as np

a = np.array([[1, 6], 
              [2, 8], 
              [3, 11],
              [3, 10],
              [1, 7]])

# alternative way

# a = np.array([[1, 2, 3, 3, 1],
             # [6, 8, 11, 10, 7]]).T

a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [67]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [68]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [85]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1]) / (a_centered.shape[0] - 1)
a_centered_sp

2.0

### Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [89]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])